### ISSUE TITLE
把isModule 改为true 运行提示找不到符号  RouterMapping_login

### ISSUE THREAD

**Issue by lengqingfeng2012** [samuelhuahui/Sun#2]
![image](https://cloud.githubusercontent.com/assets/22165968/25881603/89f3423e-3570-11e7-97ee-24e86ca6b13b.png)

**Comment by sun8829** [comment]
isModule改为true时，login就变成Application，此时主Module不会再依赖login，所以login生成的map是找不到的，这里需要修改OdyApplication把@Modules注解里的login删掉，ActivityRouter当前还不支持自动添加，后面我会引入ActivityRouter源码，把这里做成动态的。谢谢你提的宝贵意见

**Comment by sun8829** [comment]
后面会把Module的配置分开，不是通过isModule全局配置，以满足更多开发场景。
